#!/usr/bin/env bash
# Renombra platform-docs a kebab-case/inglés preservando historia (git mv).
# Requiere correrse desde la raíz del repo, con working tree limpio.
set -euo pipefail

if [ -n "$(git status --porcelain)" ]; then
  echo "El working tree no está limpio. Haz commit/stash antes de correr esto." >&2
  exit 1
fi

echo "Aplicando $( (grep -c '^git mv' "$0") 2>/dev/null || true) renames..."

git mv -- 'readme.md' 'README.md'
mkdir -p 'hsm/sprint-1.0'
git mv -- 'HSM/spring-1.0/Approach Híbrido Recomendado.md' 'hsm/sprint-1.0/recommended-hybrid-approach.md'
mkdir -p 'hsm/sprint-1.0'
git mv -- 'HSM/spring-1.0/Manifiesto Kubernetes Optimizado para Migración.yml' 'hsm/sprint-1.0/optimized-kubernetes-manifest-for-migration.yml'
mkdir -p 'hsm/sprint-1.0'
git mv -- 'HSM/spring-1.0/Plan de Migración Fase 2 (Controlado).md' 'hsm/sprint-1.0/controlled-migration-plan-phase-2.md'
mkdir -p 'architecture/sprint-0.1/decision-log'
git mv -- 'architecture/sprint-0.1/Decision Log Técnico - Entradas Críticas/DLT-001-Estrategia de Aislamiento de Datos.md' 'architecture/sprint-0.1/decision-log/DLT-001-data-isolation-strategy.md'
mkdir -p 'architecture/sprint-0.1/decision-log'
git mv -- 'architecture/sprint-0.1/Decision Log Técnico - Entradas Críticas/DLT-002-Estrategia de APIs Multi-Tenant.md' 'architecture/sprint-0.1/decision-log/DLT-002-multi-tenant-api-strategy.md'
mkdir -p 'architecture/sprint-0.1/decision-log'
git mv -- 'architecture/sprint-0.1/Decision Log Técnico - Entradas Críticas/DLT-003-Identity Management Multi-Tenant.md' 'architecture/sprint-0.1/decision-log/DLT-003-multi-tenant-identity-management.md'
mkdir -p 'architecture/sprint-0.1/decision-log'
git mv -- 'architecture/sprint-0.1/Decision Log Técnico - Entradas Críticas/DLT-004-Estrategia HSM.md' 'architecture/sprint-0.1/decision-log/DLT-004-hsm-strategy.md'
mkdir -p 'architecture/sprint-0.1/decision-log'
git mv -- 'architecture/sprint-0.1/Decision Log Técnico - Entradas Críticas/DLT-005-Service Mesh.md' 'architecture/sprint-0.1/decision-log/DLT-005-service-mesh.md'
mkdir -p 'architecture/sprint-0.1/decision-log'
git mv -- 'architecture/sprint-0.1/Decision Log Técnico - Entradas Críticas/DLT-006-Estrategia de Base de Datos.md' 'architecture/sprint-0.1/decision-log/DLT-006-database-strategy.md'
mkdir -p 'architecture/sprint-0.1/decision-log'
git mv -- 'architecture/sprint-0.1/Decision Log Técnico - Entradas Críticas/DLT-007-Auditoría.md' 'architecture/sprint-0.1/decision-log/DLT-007-audit.md'
mkdir -p 'architecture/sprint-0.1/decision-log'
git mv -- 'architecture/sprint-0.1/Decision Log Técnico - Entradas Críticas/DLT-008-Plataforma de Contenedores.md' 'architecture/sprint-0.1/decision-log/DLT-008-container-platform.md'
mkdir -p 'architecture/sprint-0.1/decision-log'
git mv -- 'architecture/sprint-0.1/Decision Log Técnico - Entradas Críticas/DLT-009-Estrategia de Cumplimiento.md' 'architecture/sprint-0.1/decision-log/DLT-009-compliance-strategy.md'
mkdir -p 'architecture/sprint-0.1/decision-log'
git mv -- 'architecture/sprint-0.1/Decision Log Técnico - Entradas Críticas/DLT-010-Monitoreo y Observabilidad.md' 'architecture/sprint-0.1/decision-log/DLT-010-monitoring-observability.md'
mkdir -p 'architecture/sprint-0.1/decision-log'
git mv -- 'architecture/sprint-0.1/Decision Log Técnico - Entradas Críticas/DLT-011-Formatos de Firma de Documentos.md' 'architecture/sprint-0.1/decision-log/DLT-011-document-signature-formats.md'
mkdir -p 'architecture/sprint-0.1/decision-log'
git mv -- 'architecture/sprint-0.1/Decision Log Técnico - Entradas Críticas/DLT-012-Continuidad de Negocio.md' 'architecture/sprint-0.1/decision-log/DLT-012-business-continuity.md'
mkdir -p 'architecture/sprint-0.1/diagrams'
git mv -- 'architecture/sprint-0.1/diagrams/multi-tenent-SaaS-platform.puml' 'architecture/sprint-0.1/diagrams/multi-tenant-saas-platform.puml'
mkdir -p 'architecture/sprint-0.1/diagrams'
git mv -- 'architecture/sprint-0.1/diagrams/system-context-C4-model.puml' 'architecture/sprint-0.1/diagrams/system-context-c4-model.puml'
mkdir -p 'architecture/sprint-0.1/integration-patterns'
git mv -- 'architecture/sprint-0.1/integration patterns/data_access_tenant_aware.java' 'architecture/sprint-0.1/integration-patterns/data-access-tenant-aware.java'
mkdir -p 'architecture/sprint-0.1/integration-patterns'
git mv -- 'architecture/sprint-0.1/integration patterns/tenant_context_propagation.java' 'architecture/sprint-0.1/integration-patterns/tenant-context-propagation.java'
mkdir -p 'architecture/sprint-0.1/integration-patterns'
git mv -- 'architecture/sprint-0.1/integration patterns/tenat_onboarding.java' 'architecture/sprint-0.1/integration-patterns/tenant-onboarding.java'
mkdir -p 'architecture/sprint-0.1/requirements'
git mv -- 'architecture/sprint-0.1/requirements/critical_multi-tenant_technical_requirements.yml' 'architecture/sprint-0.1/requirements/critical-multi-tenant-technical-requirements.yml'
mkdir -p 'architecture/sprint-0.1/requirements'
git mv -- 'architecture/sprint-0.1/requirements/multy-tenent_rgulatory_requirements.md' 'architecture/sprint-0.1/requirements/multi-tenant-regulatory-requirements.md'
mkdir -p 'architecture/sprint-0.1'
git mv -- 'architecture/sprint-0.1/stack-coretechnical-decision-log.md' 'architecture/sprint-0.1/stack-core-technical-decision-log.md'
mkdir -p 'architecture/sprint-0.2/api-specs'
git mv -- 'architecture/sprint-0.2/apis (openapi3.0) specifications/API Principal - Signing Orchestrator.yml' 'architecture/sprint-0.2/api-specs/signing-orchestrator-api.yml'
mkdir -p 'architecture/sprint-0.2/api-specs'
git mv -- 'architecture/sprint-0.2/apis (openapi3.0) specifications/Tenant Management API.yml' 'architecture/sprint-0.2/api-specs/tenant-management-api.yml'
mkdir -p 'architecture/sprint-0.2/domain-events'
git mv -- 'architecture/sprint-0.2/data model - domain events/application-kafka.yml' 'architecture/sprint-0.2/domain-events/application-kafka.yml'
mkdir -p 'architecture/sprint-0.2/domain-events'
git mv -- 'architecture/sprint-0.2/data model - domain events/data-model multi-tenant.sql' 'architecture/sprint-0.2/domain-events/data-model-multi-tenant.sql'
mkdir -p 'architecture/sprint-0.2/domain-events'
git mv -- 'architecture/sprint-0.2/data model - domain events/domain events- (Event Sourcing).java' 'architecture/sprint-0.2/domain-events/domain-events-event-sourcing.java'
mkdir -p 'architecture/sprint-0.2/microservices-technical-specifications/audit-compliance-layer'
git mv -- 'architecture/sprint-0.2/microservices-technical-specifications/Audit-Compliance Layer/audit-service (Event Sourcing).yml' 'architecture/sprint-0.2/microservices-technical-specifications/audit-compliance-layer/audit-service-event-sourcing.yml'
mkdir -p 'architecture/sprint-0.2/microservices-technical-specifications/audit-compliance-layer'
git mv -- 'architecture/sprint-0.2/microservices-technical-specifications/Audit-Compliance Layer/compliance-service.yml' 'architecture/sprint-0.2/microservices-technical-specifications/audit-compliance-layer/compliance-service.yml'
mkdir -p 'architecture/sprint-0.2/microservices-technical-specifications/audit-compliance-layer'
git mv -- 'architecture/sprint-0.2/microservices-technical-specifications/Audit-Compliance Layer/timestamp-service.yml' 'architecture/sprint-0.2/microservices-technical-specifications/audit-compliance-layer/timestamp-service.yml'
mkdir -p 'architecture/sprint-0.2/microservices-technical-specifications/certificate-keys-layer'
git mv -- 'architecture/sprint-0.2/microservices-technical-specifications/Certificate-Keys Layer/certificate-service.yml' 'architecture/sprint-0.2/microservices-technical-specifications/certificate-keys-layer/certificate-service.yml'
mkdir -p 'architecture/sprint-0.2/microservices-technical-specifications/certificate-keys-layer'
git mv -- 'architecture/sprint-0.2/microservices-technical-specifications/Certificate-Keys Layer/hsm-gateway (Critical Service).yml' 'architecture/sprint-0.2/microservices-technical-specifications/certificate-keys-layer/hsm-gateway-critical-service.yml'
mkdir -p 'architecture/sprint-0.2/microservices-technical-specifications/certificate-keys-layer'
git mv -- 'architecture/sprint-0.2/microservices-technical-specifications/Certificate-Keys Layer/ocsp-service.yml' 'architecture/sprint-0.2/microservices-technical-specifications/certificate-keys-layer/ocsp-service.yml'
mkdir -p 'architecture/sprint-0.2/microservices-technical-specifications/identity-auth-layer'
git mv -- 'architecture/sprint-0.2/microservices-technical-specifications/Identity-Auth Layer/authn-service.yml' 'architecture/sprint-0.2/microservices-technical-specifications/identity-auth-layer/authn-service.yml'
mkdir -p 'architecture/sprint-0.2/microservices-technical-specifications/identity-auth-layer'
git mv -- 'architecture/sprint-0.2/microservices-technical-specifications/Identity-Auth Layer/authz-service.yml' 'architecture/sprint-0.2/microservices-technical-specifications/identity-auth-layer/authz-service.yml'
mkdir -p 'architecture/sprint-0.2/microservices-technical-specifications/identity-auth-layer'
git mv -- 'architecture/sprint-0.2/microservices-technical-specifications/Identity-Auth Layer/identity-service (BFF Pattern).yml' 'architecture/sprint-0.2/microservices-technical-specifications/identity-auth-layer/identity-service-bff-pattern.yml'
mkdir -p 'architecture/sprint-0.2/microservices-technical-specifications/integration-api-layer'
git mv -- 'architecture/sprint-0.2/microservices-technical-specifications/Integration-API Layer/api-gateway.yml' 'architecture/sprint-0.2/microservices-technical-specifications/integration-api-layer/api-gateway.yml'
mkdir -p 'architecture/sprint-0.2/microservices-technical-specifications/integration-api-layer'
git mv -- 'architecture/sprint-0.2/microservices-technical-specifications/Integration-API Layer/notification-service.yml' 'architecture/sprint-0.2/microservices-technical-specifications/integration-api-layer/notification-service.yml'
mkdir -p 'architecture/sprint-0.2/microservices-technical-specifications/integration-api-layer'
git mv -- 'architecture/sprint-0.2/microservices-technical-specifications/Integration-API Layer/tenant-management.yml' 'architecture/sprint-0.2/microservices-technical-specifications/integration-api-layer/tenant-management.yml'
mkdir -p 'architecture/sprint-0.2/microservices-technical-specifications/signing-documents-layer'
git mv -- 'architecture/sprint-0.2/microservices-technical-specifications/Signing-Documents Layer/document-service.yml' 'architecture/sprint-0.2/microservices-technical-specifications/signing-documents-layer/document-service.yml'
mkdir -p 'architecture/sprint-0.2/microservices-technical-specifications/signing-documents-layer'
git mv -- 'architecture/sprint-0.2/microservices-technical-specifications/Signing-Documents Layer/pdf-signing-service.yml' 'architecture/sprint-0.2/microservices-technical-specifications/signing-documents-layer/pdf-signing-service.yml'
mkdir -p 'architecture/sprint-0.2/microservices-technical-specifications/signing-documents-layer'
git mv -- 'architecture/sprint-0.2/microservices-technical-specifications/Signing-Documents Layer/signing-orchestrator (Core Business Logic).yml' 'architecture/sprint-0.2/microservices-technical-specifications/signing-documents-layer/signing-orchestrator-core-business-logic.yml'
mkdir -p 'architecture/sprint-0.2/microservices-technical-specifications/signing-documents-layer'
git mv -- 'architecture/sprint-0.2/microservices-technical-specifications/Signing-Documents Layer/xml-signing-service.yml' 'architecture/sprint-0.2/microservices-technical-specifications/signing-documents-layer/xml-signing-service.yml'
mkdir -p 'architecture/sprint-0.2/migration-strategy'
git mv -- 'architecture/sprint-0.2/migrations strategy/existing data migrationd.java' 'architecture/sprint-0.2/migration-strategy/existing-data-migration.java'
mkdir -p 'architecture/sprint-0.2/migration-strategy'
git mv -- 'architecture/sprint-0.2/migrations strategy/kubertnets-deployment.yml' 'architecture/sprint-0.2/migration-strategy/kubernetes-deployment.yml'
mkdir -p 'architecture/sprint-0.2/migration-strategy'
git mv -- 'architecture/sprint-0.2/migrations strategy/multi-tenent database migration.sql' 'architecture/sprint-0.2/migration-strategy/multi-tenant-database-migration.sql'
mkdir -p 'architecture/sprint-1.0'
git mv -- 'architecture/sprint-1.0/Audit Event JSON Schema Estandarizado.json' 'architecture/sprint-1.0/standardized-audit-event-json-schema.json'
mkdir -p 'architecture/sprint-1.0/decision-log'
git mv -- 'architecture/sprint-1.0/Decision Log Técnico - Entradas Críticas/DLT-013-Adopción de SoftHSMv2 sobre HSM Hardware.md' 'architecture/sprint-1.0/decision-log/DLT-013-softhsmv2-adoption-over-hardware-hsm.md'
mkdir -p 'architecture/sprint-1.0/decision-log'
git mv -- 'architecture/sprint-1.0/Decision Log Técnico - Entradas Críticas/DLT-014-Cambio de Arquitectura.md' 'architecture/sprint-1.0/decision-log/DLT-014-architecture-change.md'
mkdir -p 'architecture/sprint-1.0/decision-log'
git mv -- 'architecture/sprint-1.0/Decision Log Técnico - Entradas Críticas/DLT-015-Cambio de Arquitectura.md' 'architecture/sprint-1.0/decision-log/DLT-015-architecture-change.md'
mkdir -p 'architecture/sprint-1.0/decision-log'
git mv -- 'architecture/sprint-1.0/Decision Log Técnico - Entradas Críticas/DLT-016-HSM-service Multitenant management.md' 'architecture/sprint-1.0/decision-log/DLT-016-hsm-service-multitenant-management.md'
mkdir -p 'architecture/sprint-1.0/decision-log'
git mv -- 'architecture/sprint-1.0/Decision Log Técnico - Entradas Críticas/DLT-017-Protocolo de Comunicación entre Microservicios - HTTP REST vs gRPC.md' 'architecture/sprint-1.0/decision-log/DLT-017-microservices-communication-protocol-http-rest-vs-grpc.md'
mkdir -p 'architecture/sprint-1.0/decision-log'
git mv -- 'architecture/sprint-1.0/Decision Log Técnico - Entradas Críticas/DLT-018-HYBRID_PKI_ARCHITECTURE.md' 'architecture/sprint-1.0/decision-log/DLT-018-hybrid-pki-architecture.md'
mkdir -p 'architecture/sprint-1.0/decision-log'
git mv -- 'architecture/sprint-1.0/Decision Log Técnico - Entradas Críticas/DLT-019-Key Rotation Strategy.md' 'architecture/sprint-1.0/decision-log/DLT-019-key-rotation-strategy.md'
mkdir -p 'architecture/sprint-1.0/decision-log'
git mv -- 'architecture/sprint-1.0/Decision Log Técnico - Entradas Críticas/DLT-020-Postergación de la implementación de OCSP.md' 'architecture/sprint-1.0/decision-log/DLT-020-ocsp-implementation-postponement.md'
mkdir -p 'architecture/sprint-1.0'
git mv -- 'architecture/sprint-1.0/Dueuda Tecnica.md' 'architecture/sprint-1.0/technical-debt.md'
mkdir -p 'architecture/sprint-1.0/diagrams/flow'
git mv -- 'architecture/sprint-1.0/diagramas/flutjo/PROCESO PRINCIPAL.md' 'architecture/sprint-1.0/diagrams/flow/main-process.md'
mkdir -p 'architecture/sprint-1.0/diagrams/flow'
git mv -- 'architecture/sprint-1.0/diagramas/flutjo/Proceso-pinricpal.puml' 'architecture/sprint-1.0/diagrams/flow/main-process.puml'
mkdir -p 'architecture/sprint-1.0/diagrams/flow'
git mv -- 'architecture/sprint-1.0/diagramas/flutjo/SUBSISTEMAS CRÍTICOS.md' 'architecture/sprint-1.0/diagrams/flow/critical-subsystems.md'
mkdir -p 'architecture/sprint-1.0/diagrams/flow/signatures'
git mv -- 'architecture/sprint-1.0/diagramas/flutjo/firmas/end-point.puml' 'architecture/sprint-1.0/diagrams/flow/signatures/endpoint.puml'
mkdir -p 'architecture/sprint-1.0/diagrams/flow/signatures'
git mv -- 'architecture/sprint-1.0/diagramas/flutjo/firmas/flujo-completo.puml' 'architecture/sprint-1.0/diagrams/flow/signatures/complete-flow.puml'
mkdir -p 'architecture/sprint-1.0/diagrams/flow/signatures'
git mv -- 'architecture/sprint-1.0/diagramas/flutjo/firmas/orden-jerarquico-extendido.puml' 'architecture/sprint-1.0/diagrams/flow/signatures/extended-hierarchical-order.puml'
mkdir -p 'architecture/sprint-1.0/diagrams/flow/signatures'
git mv -- 'architecture/sprint-1.0/diagramas/flutjo/firmas/orden-jerarquico.md' 'architecture/sprint-1.0/diagrams/flow/signatures/hierarchical-order.md'
mkdir -p 'architecture/sprint-1.0/diagrams/flow/signatures'
git mv -- 'architecture/sprint-1.0/diagramas/flutjo/firmas/orden-jerarquico.puml' 'architecture/sprint-1.0/diagrams/flow/signatures/hierarchical-order.puml'
mkdir -p 'architecture/sprint-1.0/diagrams/flow/signatures'
git mv -- 'architecture/sprint-1.0/diagramas/flutjo/firmas/subsistema-firma.puml' 'architecture/sprint-1.0/diagrams/flow/signatures/signature-subsystem.puml'
mkdir -p 'architecture/sprint-1.0/diagrams/flow'
git mv -- 'architecture/sprint-1.0/diagramas/flutjo/subsistemas-criticos-mantenimiento.puml' 'architecture/sprint-1.0/diagrams/flow/critical-subsystems-maintenance.puml'
mkdir -p 'architecture/sprint-1.0/diagrams/flow'
git mv -- 'architecture/sprint-1.0/diagramas/flutjo/subsistemas-criticos-multitenant.puml' 'architecture/sprint-1.0/diagrams/flow/critical-subsystems-multitenant.puml'
mkdir -p 'architecture/sprint-1.0/diagrams/flow'
git mv -- 'architecture/sprint-1.0/diagramas/flutjo/subsistemas-criticos-verificaciion.puml' 'architecture/sprint-1.0/diagrams/flow/critical-subsystems-verification.puml'
mkdir -p 'architecture/sprint-1.0/diagrams'
git mv -- 'architecture/sprint-1.0/diagramas/hybrid-audit-cliento-go.puml' 'architecture/sprint-1.0/diagrams/hybrid-audit-go-client.puml'
mkdir -p 'qa/sprint-0.2'
git mv -- 'qa/spring-0.2/criterios-aceptacion-estandar.md' 'qa/sprint-0.2/standard-acceptance-criteria.md'
mkdir -p 'qa/sprint-0.2'
git mv -- 'qa/spring-0.2/estrategia-testing-microservicios.md' 'qa/sprint-0.2/microservices-testing-strategy.md'
mkdir -p 'qa/sprint-0.2'
git mv -- 'qa/spring-0.2/plan-automatizacion-identity.md' 'qa/sprint-0.2/identity-automation-plan.md'
mkdir -p 'qa/sprint-0.2'
git mv -- 'qa/spring-0.2/setup-herramientas-testing.md' 'qa/sprint-0.2/testing-tools-setup.md'
mkdir -p 'qa/sprint-1.0'
git mv -- 'qa/sprint-1.0/Etapa Escalamiento (Phase 2).md' 'qa/sprint-1.0/scaling-stage-phase-2.md'
mkdir -p 'qa/sprint-1.0'
git mv -- 'qa/sprint-1.0/Métricas de Success por Fase.md' 'qa/sprint-1.0/success-metrics-by-phase.md'
mkdir -p 'qa/sprint-1.0'
git mv -- 'qa/sprint-1.0/Stack de Monitoring .md' 'qa/sprint-1.0/monitoring-stack.md'
mkdir -p 'qa/sprint-1.0'
git mv -- 'qa/sprint-1.0/Triggers de Transición.md' 'qa/sprint-1.0/transition-triggers.md'
mkdir -p 'security/sprint-0.2/cryptographic'
git mv -- 'security/spring-0.2/cryptographic/cryptographic-specification.md' 'security/sprint-0.2/cryptographic/cryptographic-specification.md'
mkdir -p 'security/sprint-0.2/multi-tenant'
git mv -- 'security/spring-0.2/multi-tenant/multi-tenant-security-plan.md' 'security/sprint-0.2/multi-tenant/multi-tenant-security-plan.md'
mkdir -p 'security/sprint-0.2/policies'
git mv -- 'security/spring-0.2/policies/security-policies.md' 'security/sprint-0.2/policies/security-policies.md'
mkdir -p 'security/sprint-0.2/threat-modeling'
git mv -- 'security/spring-0.2/threat-modeling/00-threat-modeling-methodology.md' 'security/sprint-0.2/threat-modeling/00-threat-modeling-methodology.md'
mkdir -p 'security/sprint-0.2/threat-modeling'
git mv -- 'security/spring-0.2/threat-modeling/01-identity-service-threat-model.md' 'security/sprint-0.2/threat-modeling/01-identity-service-threat-model.md'
mkdir -p 'security/sprint-0.2/threat-modeling'
git mv -- 'security/spring-0.2/threat-modeling/02-certificate-keys-layer-threat-model.md' 'security/sprint-0.2/threat-modeling/02-certificate-keys-layer-threat-model.md'
mkdir -p 'security/sprint-0.2/threat-modeling'
git mv -- 'security/spring-0.2/threat-modeling/03-signing-documents-layer-threat-model.md' 'security/sprint-0.2/threat-modeling/03-signing-documents-layer-threat-model.md'
mkdir -p 'security/sprint-0.2/threat-modeling'
git mv -- 'security/spring-0.2/threat-modeling/04-audit-compliance-layer-threat-model.md' 'security/sprint-0.2/threat-modeling/04-audit-compliance-layer-threat-model.md'
mkdir -p 'security/sprint-0.2/threat-modeling'
git mv -- 'security/spring-0.2/threat-modeling/05-integration-api-layer-threat-model.md' 'security/sprint-0.2/threat-modeling/05-integration-api-layer-threat-model.md'
mkdir -p 'security/sprint-1.0'
git mv -- 'security/spring-1.0/Arquitectura de Gestión de Secretos.md' 'security/sprint-1.0/secrets-management-architecture.md'
mkdir -p 'security/sprint-1.0'
git mv -- 'security/spring-1.0/Consideraciones de Implementación.md' 'security/sprint-1.0/implementation-considerations.md'
mkdir -p 'security/sprint-1.0'
git mv -- 'security/spring-1.0/JWT-standar.md' 'security/sprint-1.0/jwt-standard.md'
mkdir -p 'security/sprint-1.0'
git mv -- 'security/spring-1.0/Matriz de Comunicación Permitida.md' 'security/sprint-1.0/allowed-communication-matrix.md'
mkdir -p 'security/sprint-1.0'
git mv -- 'security/spring-1.0/Seguridad basica implementada.md' 'security/sprint-1.0/basic-security-implemented.md'
mkdir -p 'security/sprint-1.0'
git mv -- 'security/spring-1.0/Troubleshooting Inicial.md' 'security/sprint-1.0/initial-troubleshooting.md'
mkdir -p 'security/sprint-1.0'
git mv -- 'security/spring-1.0/Verificación de Policies.md' 'security/sprint-1.0/policy-verification.md'
mkdir -p 'security/sprint-1.0/policies'
git mv -- 'security/spring-1.0/policies/API Gateway to Backend Services.md' 'security/sprint-1.0/policies/api-gateway-to-backend-services.md'
mkdir -p 'security/sprint-1.0/policies'
git mv -- 'security/spring-1.0/policies/Audit Service Collection.md' 'security/sprint-1.0/policies/audit-service-collection.md'
mkdir -p 'security/sprint-1.0/policies'
git mv -- 'security/spring-1.0/policies/Backend Services to API Gateway.md' 'security/sprint-1.0/policies/backend-services-to-api-gateway.md'
mkdir -p 'security/sprint-1.0/policies'
git mv -- 'security/spring-1.0/policies/Crypto Services Communication.md' 'security/sprint-1.0/policies/crypto-services-communication.md'
mkdir -p 'security/sprint-1.0/policies'
git mv -- 'security/spring-1.0/policies/DNS Resolution Essential.md' 'security/sprint-1.0/policies/dns-resolution-essential.md'
mkdir -p 'security/sprint-1.0/policies'
git mv -- 'security/spring-1.0/policies/External Database Access.md' 'security/sprint-1.0/policies/external-database-access.md'
mkdir -p 'security/sprint-1.0/policies'
git mv -- 'security/spring-1.0/policies/Identification Service to Redis.md' 'security/sprint-1.0/policies/identification-service-to-redis.md'
mkdir -p 'security/sprint-1.0/policies'
git mv -- 'security/spring-1.0/policies/Policy Default-Deny (Base).md' 'security/sprint-1.0/policies/policy-default-deny-base.md'
mkdir -p 'standards'
git mv -- 'standards/achitecture-doc-template.md' 'standards/architecture-doc-template.md'
mkdir -p 'standards'
git mv -- 'standards/aprobation-workflow.puml' 'standards/approval-workflow.puml'

# Limpia directorios que quedaron vacíos tras los moves
find . -type d -empty -not -path "./.git*" -delete

echo "Listo: 105 archivos movidos."
git status --short | head -30